# Generated by Django 4.2.6 on 2023-10-24 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('place', models.CharField(max_length=100)),
                ('dept', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('profile', models.ImageField(upload_to='employee_profiles')),
            ],
        ),
    ]
